### PR TITLE
Avoid MSVC120 runtime dependency for Lua Windows DLLs

### LINKED ISSUE #7363: Nuget-provided windows dependencies don't work for many players
playtest-20150118 would not run for many people, and we had to work around this by manually packaging a new installer with the dlls from release-20141029.  I expect this to be a regression from #7346, which I suspect will be caused by the nuget-provided dlls linking against one or more VC runtimes that some people don't have installed.

If this is indeed the problem, then it is a bit crap to expect players to install N different C runtimes before they can run OpenRA, so we should revert back to our previous working libraries.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7888831-nuget-provided-windows-dependencies-don-t-work-for-many-players?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes https://github.com/OpenRA/OpenRA/issues/7363.

Essentially the same thing we did in https://github.com/OpenRA/OpenRA/pull/7212, but this time for `lua51.dll` as well.

### CODE REVIEW

**Comment by obrakmann** [comment]
according to [dependency walker](http://www.dependencywalker.com/), all our libs depend on either mscoree.dll, msvcrt.dll or msvcr110.dll. except zlib, which depends on msvcr120.dll.

Note that even the lua51.dll depends on msvcr110.dll. I assume that's a packaging error (for the nuget package) and the file ended up in the wrong directory.

Anyway, we should probably fix the zlib1.dll instead (if possible) and as a bonus include the ms vc 2011 redist in our nsis package: http://voidknot.blogspot.de/2013/12/shipping-visual-studio-redistributable.html

**Comment by Mailaender** [comment]
Updated this to include the `zlib1.dll` Windows dependency. My mistake. Did not know what these version numbers in the folders mean. I thought latest is greatest when filing https://github.com/OpenRA/OpenRA/pull/7346, but forgot that Microsoft still has not properly solved the DLL hell problem after all those years.

File: thirdparty/fetch-thirdparty-deps-windows.sh [hunk 1]
```diff
@@ -24,14 +24,14 @@ fi
...
-	cp ./lua51.redist.5.1.5/build/native/bin/Win32/v120/Release/lua5.1.dll ./windows/lua51.dll
+	cp ./lua51.redist.5.1.5/build/native/bin/Win32/v110/Release/lua5.1.dll ./windows/lua51.dll
 	rm -rf lua51.redist.5.1.5
 fi
 
 if [ ! -f windows/zlib1.dll ]; then
 	echo "Fetching ZLib from nuget"
 	nuget install zlib.redist -Version 1.2.8.7
-	cp ./zlib.redist.1.2.8.7/build/native/bin/v120/Win32/Release/dynamic/stdcall/zlib.dll windows/zlib1.dll
+	cp ./zlib.redist.1.2.8.7/build/native/bin/v100/Win32/Release/dynamic/stdcall/zlib.dll windows/zlib1.dll
```
Comment (obrakmann) [inline thirdparty/fetch-thirdparty-deps-windows.sh]: v110, please

Comment (Mailaender) [inline thirdparty/fetch-thirdparty-deps-windows.sh]: Done.

**Comment by obrakmann** [comment]
Ok, let's try this. At least we can then state a single msvc redist as dependency. :+1:

**Comment by Mailaender** [comment]
> Anyway, we should probably fix the zlib1.dll instead (if possible) and as a bonus include the ms vc 2011 redist in our nsis package: http://voidknot.blogspot.de/2013/12/shipping-visual-studio-redistributable.html

I filed https://github.com/OpenRA/OpenRA/pull/7609 for that.

**Comment by Mailaender** [comment]
Updated to make use of https://www.nuget.org/packages/lua.binaries/5.1.5 instead. This now depends on MS Visual C++ 8.0 Runtime which is the oldest dependency available at http://sourceforge.net/projects/luabinaries/files/5.1.5/Windows%20Libraries/Dynamic/.

**Comment by penev92** [comment]
Works! :+1: 
Thank you!

**Comment by penev92** [comment]
I tested on 3 different Windows 7 machines, including my own dev machine.
Bleed runs only on mine (since I have a lot of stuff from VisualStudio).
The changed fetch script makes it run on all 3.

**Comment by penev92** [comment]
As a continuation from #7611:
>[02:21] <+Scott`> both work
[02:21] <+Scott`> now leave me alone

Still good enough.
