### PR TITLE
Fix a crash in soviet05

### LINKED ISSUE #16204: Soviet 05 Distant Thunder script error
I completed the "Kill all Units and Structures" objective before trying to capture the green Radar Dome, the mission immediately crashed before I could capture the Radar Dome.

Might be unrelated but I also sequence-broke the mission by killing the MCV before it could leave the mainland with Yaks.

ra1 crash

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #16204.

Any objections if I remove the `ObjectiveMet` sound (in a follow-up)? We are not consistently playing it on all missions and it overlaps with the capture notification (we could delay that one instead, though).

### CODE REVIEW

File: mods/ra/maps/soviet-05/soviet05.lua [hunk 1]
```diff
@@ -144,7 +144,10 @@ end
 Tick = function()
 	if Greece.HasNoRequiredUnits() and GoodGuy.HasNoRequiredUnits() then
 		player.MarkCompletedObjective(KillAll)
-		player.MarkCompletedObjective(HoldObjective)
+
+		if HoldObjective then
```
Comment (reaperrr) [inline mods/ra/maps/soviet-05/soviet05.lua]: Since I'm not so good with our lua scripts and couldn't find the info in our code:
How exactly does this check work? Do objectives return a boolean value, or does this just check if it's not null?

Comment (abcdefg30) [reply mods/ra/maps/soviet-05/soviet05.lua]: Check if it the variable is not null (or true, but it won't be true).

Comment (pchote) [reply mods/ra/maps/soviet-05/soviet05.lua]: https://logs.openra.net/index.php?year=2019&month=02&day=23#22:09:59

**Review by pchote — APPROVED** [review]
As mentioned in IRC, I don't really like how you can end up with two different sets of primary objectives depending on how you complete the mission. It would be better if it granted and then immediately completed the hold objective instead.

Otherwise, :+1: and I don't think this should block the playtest so merging as-is.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/c514a17b92414f89220029cd64b4f65b2dec092c
c41d2aee5594a1812b1c89af6c0b3373e77c0bdb
