### PR TITLE
Fix funpark01 failing at mission start

### LINKED ISSUE #13571: [bleed branch] Tiberian Dawn Strange behavior mission failed when start.
build on 2017-06-30 on debian 8.8 i386
strange behave
Start the mission and have no time do anything, the Misstion Failed conversation window appear.

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #13571.

### CODE REVIEW

File: mods/cnc/maps/funpark01/scj01ea.lua [hunk 1]
```diff
@@ -84,7 +84,7 @@ WorldLoaded = function()
 	Trigger.OnIdle(DinoTrex, DinoTrex.Hunt)
 
 	ReinforceWithLandingCraft(RifleReinforcments, SeaEntryA.Location, BeachReinforceA.Location, BeachReinforceA.Location)
-	Trigger.AfterDelay(DateTime.Seconds(1), function() InitialUnitsArrived = true end)
+	Trigger.AfterDelay(DateTime.Seconds(3), function() InitialUnitsArrived = true end)
```
Comment (reaperrr) [inline mods/cnc/maps/funpark01/scj01ea.lua]: Out of curiosity, why does 1 crash?

**Review by reaperrr — APPROVED** [review]

File: mods/cnc/maps/funpark01/scj01ea.lua (hunk 1 above)
Comment (abcdefg30) [inline mods/cnc/maps/funpark01/scj01ea.lua]: The boolean controls when we start to check for living player units. For some reason the first units are added to world later than one second into the game. I have to admit that I don't know the exact cause of this, we're at bisecting at the moment.
> 00:17:17 (pchote) abcdefg30: what's the deal with the dino mission?
00:17:27 (pchote) why does that fix it?
00:17:50 (pchote) and what regressed it in the first place?
00:17:55 (abcdefg30) if that boolean is set to true we check if the player has any units which are Required
00:18:04 (abcdefg30) I don't know what regressed, that's the scary bit
00:18:10 (abcdefg30) something with unloading maybe
00:18:33 (pchote) we really need to find this out
00:18:40 (abcdefg30) the transport unloads units, and after those are added to the world, we want to check if the player has any more units remaining
00:18:41 (pchote) because other missions have probably broken too
00:18:52 (abcdefg30) meh, I already thought you'll say that
00:18:55 (abcdefg30) ^^
00:19:03 (pchote) because you know i'm right :P
00:19:03 (abcdefg30) what about git blaming it?
00:19:07 (abcdefg30) yeah
00:19:16 (abcdefg30) either way, the 3 seconds won't hurt
00:19:26 (pchote) I agree

Comment (pchote) [inline mods/cnc/maps/funpark01/scj01ea.lua]: The "regression" was introduced by 404086370774298a338027ef582a96e9a31fdcbf, which appears to have fixed an issue that was causing the landing craft reinforcement to insert its passengers into the world too early.  Failing 1-second was the technically correct behaviour, because the player *doesn't* have any of the required units (in the world) at this point in the mission.

Of course this means that we will now need to check all the other missions that use a similar script pattern.

Comment (reaperrr) [inline mods/cnc/maps/funpark01/scj01ea.lua]: gdi01 doesn't crash, fwiw, so we don't need to check that.

**Review by pchote — APPROVED** [review]
