### PR TITLE
Fix soviet-06 harvester production crash

### LINKED ISSUE #21753: Game crashed during RA Soviet mission 6b
## System Information

- Operating System:  Windows (X64, Microsoft Windows NT 10.0.19045.0)
- Runtime Version: .NET CLR 6.0.36
- OpenRA Version: playtest-20241228
- OpenRA Mod: playtest-20241228
- Source: Official download package

## Exception log

```
Exception of type `Eluant.LuaException`: [string "--[[..."]:78: attempt to call field 'FindResources' (a nil value)
   at Eluant.LuaRuntime.Call(IList`1 args)
   at Eluant.LuaRuntime.Call(LuaFunction fn, IList`1 args)
   at Eluant.LuaFunction.Call(IList`1 args)
   at Eluant.LuaFunction.Call(LuaValue[] args)
   at OpenRA.Mods.Common.Scripting.ClassicProductionQueueProperties.<>c__DisplayClass3_1.<Build>g__ProductionHandler|2(Actor factory, Actor unit)
   at OpenRA.Mods.Common.Scripting.ClassicProductionQueueProperties.<>c__DisplayClass2_0.<.ctor>g__GlobalProductionHandler|0(Actor factory, Actor unit)
   at OpenRA.Mods.Common.Scripting.ScriptTriggers.OpenRA.Mods.Common.Traits.INotifyOtherProduction.UnitProducedByOther(Actor self, Actor producee, Actor produced, String productionType, TypeDictionary init)
   at OpenRA.Mods.Common.Traits.Production.<>c__DisplayClass7_0.<DoProduction>b__0(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```

## Replay

[ra-2025-02-20T145708Z.zip](https://github.com/user-attachments/files/18888778/ra-2025-02-20T145708Z.zip)

### PR DESCRIPTION
**Pull request by JovialFeline**
Fixes https://github.com/OpenRA/OpenRA/issues/21753

A crash can occur on either soviet-06 map when a bot harvester is killed and the rebuild is done before the factory is destroyed.

This PR should fix that and a smaller issue where Allied vehicle production can unintentionally halt because a second Build is immediately called.

### CODE REVIEW

File: mods/ra/maps/soviet-06b/soviet06b-AI.lua [hunk 1]
```diff
@@ -68,15 +69,18 @@ ProduceArmor = function(factory)
...
 	if GreeceMoney() < Actor.Cost("harv") then
 		return
 	end
 
 	local toBuild = { "harv" }
-	Greece.Build(toBuild, function(unit)
-		unit.FindResources()
-		ProduceArmor(factory)
+	Greece.Build(toBuild, function(units)
+		units[1].FindResources()
```
Comment (PunkPun) [inline mods/ra/maps/soviet-06b/soviet06b-AI.lua]: This call is completelly unnecesary. Harvesters find resources when built by default

**Review by PunkPun — APPROVED** [review]

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/347857ab0ed8dd985fac9ab6d221833e11f5b2f1...3c5ecc5684e3d9be4bc8926fad88d107931a4692)

https://github.com/OpenRA/OpenRA/commit/82ee3d779c1878aa57c54c4e21a2ca4d54a1bf42
