### PR TITLE
Let the remaing enemy troops in Allies02 attack the player

### LINKED ISSUE #15837: Red Alert: Bug in scg02ea when enemy is destroyed before convoy leaves
### Issue Summary

In the second Allies mission "Five to one" there is a bug:
The mission does not end sucessfully when you manage to kill all soviet units/buildings BEFORE the convoy leaves the map. This leaves the game playable and it does never end.

My guess is:
There is a condition for checking for destruction of a building or unit after the convoy leaves. And if there are not anymore left, the game is won. But if there is nothing to destroy anymore you can never reach that condition.

#### System Information
- **Operating System:** Arch Linux x64
- **.NET / Mono Version:** not installed
- **OpenRA Version:**  release-20180923
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	1. Rush to the base and start killing
	2. While you do that build some units and kill the guards on the way of the convoy
	3. Make sure you destroy all builds before the convoy leaves the map.

### Replay

[OpenRA-2018-11-16T114750Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/2596818/OpenRA-2018-11-16T114750Z.orarep.zip)

#### Info:

I will look into it myself as i want to help with making missions but i just want to catalog it here.

### PR DESCRIPTION
**Pull request by abcdefg30**
Closes #15837.

### CODE REVIEW

**Review by pchote — APPROVED** [review]
Improvement confirmed and script changes LGTM.

File: mods/ra/maps/allies-02/allies02.lua [hunk 1]
```diff
@@ -87,6 +89,14 @@ RunInitialActivities = function()
 		SendTrucks()
 	end)
 
+	Trigger.OnAllKilled(SovietBase, function()
+		Utils.Do(ussr.GetGroundAttackers(), function(unit)
```
Comment (pchote) [inline mods/ra/maps/allies-02/allies02.lua]: Idea for future improvement: Add a `Utils.Except` helper, so this could simplify to
```lua
Utils.Do(Utils.Except(ussr.GetGroundAttackers(), PathGuards), function(unit)
    Trigger.OnIdle(unit, unit.Hunt)
end)
```

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/201faf797c9aee6b76eafd6d256d2ae21fc4999a

0777fe534dc2ff2bf7d7a7782023e626f2574d7e
b16742465418571589cc5bc645c95e0c2ae51648
