### PR TITLE
Make normal difficulty on allies06b easier

### LINKED ISSUE #16146: Allied mission 06b (Cripple Iron Curtain Research): explosive barrels don't destroy fire towers
### Issue Summary
I'm having trouble with this mission and looked up a strategy video. You can see in this video that shooting the barrels destroys the fire towers, while in OpenRA it only does minor damage.
https://youtu.be/oOtVfflViRg?list=PL-Ecy11VjzuxNt4IRF9st-BELMUSGwwQ9&t=199

#### System Information
- **Operating System:** Ubuntu 18.10
- **.NET / Mono Version:** Mono
- **OpenRA Version:** release-20181215
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	1. Start the mission
	2. Shoot a barrel with a ship

### PR DESCRIPTION
**Pull request by abc013**
Closes #16146.

When destroying the barrels on `normal`, the flamethrowers now get destroyed as well. In order to make it harder than `easy`, the flamethrowers will not be revealed by a camera.

### CODE REVIEW

**Review by Smittytron — DISMISSED** [review]

File: mods/ra/maps/allies-06b/allies06b.lua [hunk 1]
```diff
@@ -220,15 +220,15 @@ WorldLoaded = function()
...
-			Trigger.OnKilled(DefBrl1, function(a, b)
-				DefenseFlame1.Kill()
-			end)
-			Trigger.OnKilled(DefBrl2, function(a, b)
-				DefenseFlame2.Kill()
-			end)
-		end
+	if Map.LobbyOption("difficulty") ~= "hard" then
+		Trigger.OnKilled(DefBrl1, function(a, b)
+			DefenseFlame1.Kill()
```
Comment (abcdefg30) [inline mods/ra/maps/allies-06b/allies06b.lua]: We should probably add an `IsDead` check here to prevent a crash when you destroy the flamers before touching the barrels.

**Review by abcdefg30 — COMMENTED** [review]
Looks reasonable otherwise.

**Comment by abc013** [comment]
Updated.

**Review by abcdefg30 — APPROVED** [review]
The mission is still trash, but changes here LGTM.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/7062991a9a2c75c9455378fe65723677962a824d...3706b7b1e9ece6089882f41910c433093be962dd)

https://github.com/OpenRA/OpenRA/commit/94aa3106126981004294b2e7c103a9beae17ae95
https://github.com/OpenRA/OpenRA/commit/4ad4e143b756c7b75522eea584aaa187669a5902
