### PR TITLE
Fix and rebalance Fort Lonestar

### LINKED ISSUE #10100: No build progress on Fort Lonestar
On playtest 20151115.

In a game of 3, I was bottom left (top left was missing) there was no build status bar on my barracks. I could see everyone else's.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28584145-no-build-progress-on-fort-lonestar?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
This solves some crashes and also tries to make the minigame playable again
(and introduces different difficulties).

Fixes #10100.

### CODE REVIEW

File: mods/ra/maps/fort-lonestar/fort-lonestar.lua [hunk 1]
```diff
@@ -12,90 +6,62 @@ OilDerricks = { OilDerrick1, OilDerrick2, OilDerrick3, OilDerrick4 }
 SpawnPoints = { Spawn1, Spawn2, Spawn3, Spawn4 }
 Snipers = { Sniper1, Sniper2, Sniper3, Sniper4, Sniper5, Sniper6, Sniper7, Sniper8, Sniper9, Sniper10, Sniper11, Sniper12 }
 
+if Map.Difficulty == "1 Player" then
```
Comment (pchote) [inline mods/ra/maps/fort-lonestar/fort-lonestar.lua]: Wouldn't it be better to count the actual number of players instead of forcing people to select the right option?

File: mods/ra/maps/fort-lonestar/fort-lonestar.lua [hunk 2]
```diff
@@ -108,31 +74,43 @@ SendUnits = function(entryCell, unitTypes, interval, targetCell)
...
+		end)
 
-		if not played then
-			played = true
-			Utils.Do(players, function(player)
-				Media.PlaySpeechNotification(player, "EnemyUnitsApproaching")
-			end)
-			Trigger.AfterDelay(DateTime.Seconds(1), function() played = false end)
+		if (Wave < #Waves) then
+			if Utils.RandomInteger(1, 101) <= ParaChance then
```
Comment (pchote) [inline mods/ra/maps/fort-lonestar/fort-lonestar.lua]: style nit: `Utils.RandomInteger(0, 100)`

File: mods/ra/maps/fort-lonestar/fort-lonestar.lua (hunk 1 above)
Comment (abcdefg30) [inline mods/ra/maps/fort-lonestar/fort-lonestar.lua]: I thought when people want to play on an easier level they can just choose a different "Player-difficulty" (e.g. 3 players playing with the difficulty "2 Players")
instead of using easy/normal/hard and extra scaling those with the player count.

File: mods/ra/maps/fort-lonestar/fort-lonestar.lua (hunk 2 above)
Comment (abcdefg30) [inline mods/ra/maps/fort-lonestar/fort-lonestar.lua]: https://github.com/OpenRA/OpenRA/pull/9659#discussion_r43587949

File: mods/ra/maps/fort-lonestar/fort-lonestar.lua (hunk 1 above)
Comment (Phrohdoh) [inline mods/ra/maps/fort-lonestar/fort-lonestar.lua]: Maybe your idea would be better conveyed with calling this handicaps instead of making it appear to be a player count.

File: mods/ra/maps/fort-lonestar/fort-lonestar.lua (hunk 2 above)
Comment (pchote) [inline mods/ra/maps/fort-lonestar/fort-lonestar.lua]: You can change the `<=` to `<`

File: mods/ra/maps/fort-lonestar/fort-lonestar.lua (hunk 1 above)
Comment (abcdefg30) [inline mods/ra/maps/fort-lonestar/fort-lonestar.lua]: I'm still not really convinced, the difficulties resemble the suggested player count for that difficulty. A problem here might be, that players could think that "normal" means really "normal" (and thus play on that). But in this case it would be the same like "2 Players" which would be really easy for 4 players.

Comment (abcdefg30) [inline mods/ra/maps/fort-lonestar/fort-lonestar.lua]: Anyway, I'm going to change that now to `Very Easy (1P)`, `Easy (2P)`, `Normal (3P)` and `Hard (4P)`.

**Comment by abcdefg30** [comment]
Updated.

**Comment by abcdefg30** [comment]
Depends on #10244 now.

File: mods/ra/maps/fort-lonestar/map.yaml [hunk 3]
```diff
@@ -23,12 +23,13 @@ Videos:
...
 	Fog: True
 	Shroud: True
-	AllyBuildRadius: False
+	AllyBuildRadius: True
 	FragileAlliances: False
 	StartingCash: 50
 	TechLevel: Unrestricted
 	ConfigurableStartingUnits: False
 	ShortGame: False
+	Difficulties: Hard (4P), Normal (3P), Easy (2P), Very Easy (1P), Real tough guy
```
Comment (Mailaender) [inline mods/ra/maps/fort-lonestar/map.yaml]: Reading player numbers here I wonder if auto-detection via `Player.GetPlayers` from the Lua API might be more comfortable?

Comment (penev92) [inline mods/ra/maps/fort-lonestar/map.yaml]: People might still want an easier/harder option that the automatically-picked one.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/10244 has been merged. This needs to include those changes now I guess.

**Comment by abcdefg30** [comment]
Updated.
Actually only the last three commits are new, the rest is #10244 (squashed a bit).

Anyway, we should wait for the fix for #10207 as the new commits add ugly workarounds for that.

**Comment by cjshmyr** [comment]
Also fixes #9938

**Comment by abcdefg30** [comment]
It should fix that, but I think we should do some test games again. The last minute change introducing shock troopers and tesla tanks to replace the "weird" units made it a bit more diffiult than I thought. On @SoScared's last stream people got killed of quite fast.

**Comment by pchote** [comment]
#10207 is now fixed.

**Comment by abcdefg30** [comment]
Updated and rebased.

File: mods/ra/maps/fort-lonestar/map.yaml [hunk 4]
```diff
@@ -546,12 +533,28 @@ Rules:
...
+			Effect: invuln
+			Notification: ironcur9.aud
+			Upgrades: invulnerability
+			Duration: 1200
+		ExplodeCrateAction@bigboom:
+			Weapon: SCUD
+			SelectionShares: 5
+		GiveMcvCrateAction:
+			SelectionShares: 10000
+			#NoBaseSelectionShares: 100
```
Comment (Mailaender) [inline mods/ra/maps/fort-lonestar/map.yaml]: I assume these are left-overs from testing?

Comment (abcdefg30) [inline mods/ra/maps/fort-lonestar/map.yaml]: Yep, fixed. Thanks. ^^

**Comment by Mailaender** [comment]
Diff compared to https://github.com/OpenRA/OpenRA/pull/10244:

```diff
 mods/ra/maps/fort-lonestar/fort-lonestar.lua |  30 ++--
 mods/ra/maps/fort-lonestar/map.yaml          | 234 ++++++++++++---------------
 2 files changed, 109 insertions(+), 155 deletions(-)

diff --git a/mods/ra/maps/fort-lonestar/fort-lonestar.lua b/mods/ra/maps/fort-lonestar/fort-lonestar.lua
index 0717c3d..411394f 100644
--- a/mods/ra/maps/fort-lonestar/fort-lonestar.lua
+++ b/mods/ra/maps/fort-lonestar/fort-lonestar.lua
@@ -5,14 +5,6 @@ ParadropWaypoints = { Paradrop1, Paradrop2, Paradrop3, Paradrop4 }
 SpawnPoints = { Spawn1, Spawn2, Spawn3, Spawn4 }
 Snipers = { Sniper1, Sniper2, Sniper3, Sniper4, Sniper5, Sniper6, Sniper7, Sniper8, Sniper9, Sniper10, Sniper11, Sniper12 }
 
-Walls =
-{
-	{ WallTopRight1, WallTopRight2, WallTopRight3, WallTopRight4, WallTopRight5, WallTopRight6, WallTopRight7, WallTopRight8, WallTopRight9 },
-	{ WallTopLeft1, WallTopLeft2, WallTopLeft3, WallTopLeft4, WallTopLeft5, WallTopLeft6, WallTopLeft7, WallTopLeft8, WallTopLeft9 },
-	{ WallBottomLeft1, WallBottomLeft2, WallBottomLeft3, WallBottomLeft4, WallBottomLeft5, WallBottomLeft6, WallBottomLeft7, WallBottomLeft8, WallBottomLeft9 },
-	{ WallBottomRight1, WallBottomRight2, WallBottomRight3, WallBottomRight4, WallBottomRight5, WallBottomRight6, WallBottomRight7, WallBottomRight8, WallBottomRight9 }
-}
-
 if Map.Difficulty == "Very Easy (1P)" then
 	ParaChance = 20
 	Patrol = { "e1", "e2", "e1" }
@@ -92,13 +84,19 @@ SendUnits = function(entryCell, unitTypes, targetCell, extraData)
 			return
 		end
 
-		a.AttackMove(targetCell)
 		Trigger.OnIdle(a, function(a)
-			a.Hunt()
+			if a.Location ~= targetCell then
+				a.AttackMove(targetCell)
+			else
+				a.Hunt()
+			end
 		end)
 
 		if extraData == "IronCurtain" then
-			a.GrantTimedUpgrade("invulnerability", DateTime.Seconds(25))
+			a.GrantUpgrade("invulnerability")
+			Trigger.AfterDelay(DateTime.Seconds(25), function()
+				a.RevokeUpgrade("invulnerability")
+			end)
 		end
 	end)
 end
@@ -186,14 +184,6 @@ Tick = function()
 	end
 end
 
-SetupWallOwners = function()
-	Utils.Do(players, function(player)
-		Utils.Do(Walls[player.Spawn], function(wall)
-			wall.Owner = player
-		end)
-	end)
-end
-
 WorldLoaded = function()
 	soviets = Player.GetPlayer("Soviets")
 	players = { }
@@ -204,8 +194,6 @@ WorldLoaded = function()
 
 	Media.DisplayMessage("Defend Fort Lonestar at all costs!")
 
-	SetupWallOwners()
-
 	ParaProxy = Actor.Create("powerproxy.paratroopers", false, { Owner = soviets })
 	SendWave()
 end
diff --git a/mods/ra/maps/fort-lonestar/map.yaml b/mods/ra/maps/fort-lonestar/map.yaml
index e78be35..c6470d9 100644
--- a/mods/ra/maps/fort-lonestar/map.yaml
+++ b/mods/ra/maps/fort-lonestar/map.yaml
@@ -1,4 +1,4 @@
-MapFormat: 8
+MapFormat: 7
 
 RequiresMod: ra
 
@@ -83,7 +83,7 @@ Players:
 		Faction: soviet
 		LockTeam: True
 		Team: 2
-		Color: FF0101
+		ColorRamp: 0,255,128
 		Enemies: Multi0, Multi1, Multi2, Multi3
 
 Actors:
@@ -153,6 +153,9 @@ Actors:
 	Actor73: tc05
 		Location: 16,34
 		Owner: Neutral
+	Actor84: brik
+		Location: 35,25
+		Owner: Neutral
 	Actor32: tc01
 		Location: 8,24
 		Owner: Neutral
@@ -162,6 +165,27 @@ Actors:
 	Actor5: tc01
 		Location: 44,44
 		Owner: Neutral
+	Actor67: brik
+		Location: 29,25
+		Owner: Neutral
+	Actor41: brik
+		Location: 25,25
+		Owner: Neutral
+	Actor56: brik
+		Location: 26,25
+		Owner: Neutral
+	Actor85: brik
+		Location: 39,26
+		Owner: Neutral
+	Actor81: brik
+		Location: 38,25
+		Owner: Neutral
+	Actor65: brik
+		Location: 27,25
+		Owner: Neutral
+	Actor66: brik
+		Location: 28,25
+		Owner: Neutral
 	Actor51: t08
 		Location: 55,46
 		Owner: Neutral
@@ -189,6 +213,12 @@ Actors:
 	Actor17: tc03
 		Location: 54,26
 		Owner: Neutral
+	Actor83: brik
+		Location: 36,25
+		Owner: Neutral
+	Actor197: brik
+		Location: 39,37
+		Owner: Neutral
 	Actor11: tc04
 		Location: 20,53
 		Owner: Neutral
@@ -204,6 +234,15 @@ Actors:
 	Actor1: t05
 		Location: 29,16
 		Owner: Neutral
+	Actor82: brik
+		Location: 37,25
+		Owner: Neutral
+	Actor86: brik
+		Location: 39,27
+		Owner: Neutral
+	Actor80: brik
+		Location: 39,25
+		Owner: Neutral
 	Actor71: tc02
 		Location: 15,40
 		Owner: Neutral
@@ -231,6 +270,42 @@ Actors:
 	Actor52: t12
 		Location: 44,53
 		Owner: Neutral
+	Actor87: brik
+		Location: 39,28
+		Owner: Neutral
+	Actor91: brik
+		Location: 37,39
+		Owner: Neutral
+	Actor196: brik
+		Location: 39,38
+		Owner: Neutral
+	Actor195: brik
+		Location: 39,39
+		Owner: Neutral
+	Actor45: brik
+		Location: 25,28
+		Owner: Neutral
+	Actor92: brik
+		Location: 39,29
+		Owner: Neutral
+	Actor194: brik
+		Location: 38,39
+		Owner: Neutral
+	Actor55: brik
+		Location: 25,39
+		Owner: Neutral
+	Actor200: brik
+		Location: 28,39
+		Owner: Neutral
+	Actor233: brik
+		Location: 29,39
+		Owner: Neutral
+	Actor240: brik
+		Location: 39,35
+		Owner: Neutral
+	Actor199: brik
+		Location: 27,39
+		Owner: Neutral
 	Actor28: tc01
 		Location: 24,54
 		Owner: Neutral
@@ -264,114 +339,39 @@ Actors:
 	Actor68: tc05
 		Location: 35,7
 		Owner: Neutral
-	WallTopLeft1: brik
-		Location: 25,28
-		Owner: Neutral
-	WallTopLeft2: brik
-		Location: 25,27
-		Owner: Neutral
-	WallTopLeft3: brik
-		Location: 25,26
-		Owner: Neutral
-	WallTopLeft4: brik
-		Location: 25,29
-		Owner: Neutral
-	WallTopLeft5: brik
-		Location: 29,25
-		Owner: Neutral
-	WallTopLeft6: brik
-		Location: 25,25
-		Owner: Neutral
-	WallTopLeft7: brik
-		Location: 26,25
-		Owner: Neutral
-	WallTopLeft8: brik
-		Location: 27,25
-		Owner: Neutral
-	WallTopLeft9: brik
-		Location: 28,25
-		Owner: Neutral
-	WallTopRight1: brik
-		Location: 35,25
-		Owner: Neutral
-	WallTopRight2: brik
-		Location: 36,25
-		Owner: Neutral
-	WallTopRight3: brik
-		Location: 37,25
-		Owner: Neutral
-	WallTopRight4: brik
-		Location: 38,25
-		Owner: Neutral
-	WallTopRight5: brik
-		Location: 39,25
-		Owner: Neutral
-	WallTopRight6: brik
-		Location: 39,26
-		Owner: Neutral
-	WallTopRight7: brik
-		Location: 39,27
-		Owner: Neutral
-	WallTopRight8: brik
-		Location: 39,28
-		Owner: Neutral
-	WallTopRight9: brik
-		Location: 39,29
-		Owner: Neutral
-	WallBottomRight1: brik
-		Location: 39,37
-		Owner: Neutral
-	WallBottomRight2: brik
-		Location: 37,39
-		Owner: Neutral
-	WallBottomRight3: brik
-		Location: 39,38
-		Owner: Neutral
-	WallBottomRight4: brik
-		Location: 39,39
-		Owner: Neutral
-	WallBottomRight5: brik
-		Location: 38,39
-		Owner: Neutral
-	WallBottomRight6: brik
-		Location: 39,35
-		Owner: Neutral
-	WallBottomRight7: brik
+	Actor239: brik
 		Location: 39,36
 		Owner: Neutral
-	WallBottomRight8: brik
+	Actor89: brik
 		Location: 35,39
 		Owner: Neutral
-	WallBottomRight9: brik
+	Actor90: brik
 		Location: 36,39
 		Owner: Neutral
-	WallBottomLeft1: brik
-		Location: 25,39
-		Owner: Neutral
-	WallBottomLeft2: brik
-		Location: 28,39
-		Owner: Neutral
-	WallBottomLeft3: brik
-		Location: 29,39
-		Owner: Neutral
-	WallBottomLeft4: brik
-		Location: 27,39
-		Owner: Neutral
-	WallBottomLeft5: brik
+	Actor237: brik
 		Location: 25,35
 		Owner: Neutral
-	WallBottomLeft6: brik
+	Actor236: brik
 		Location: 25,36
 		Owner: Neutral
-	WallBottomLeft7: brik
+	Actor235: brik
 		Location: 25,37
 		Owner: Neutral
-	WallBottomLeft8: brik
+	Actor234: brik
 		Location: 25,38
 		Owner: Neutral
-	WallBottomLeft9: brik
+	Actor44: brik
+		Location: 25,27
+		Owner: Neutral
+	Actor43: brik
+		Location: 25,26
+		Owner: Neutral
+	Actor198: brik
 		Location: 26,39
 		Owner: Neutral
+	Actor88: brik
+		Location: 25,29
+		Owner: Neutral
 	Sniper1: sniper.soviets
 		Location: 9,26
 		Owner: Soviets
@@ -495,14 +495,14 @@ Rules:
 		WeatherOverlay:
 			WindTick: 150, 550
 			UseSquares: false
+			ParticleSize: 0, 0
 			ScatterDirection: 0, 0
 			Gravity: 8.00, 12.00
 			SwingOffset: 0, 0
 			SwingSpeed: 0, 0
 			SwingAmplitude: 0, 0
-			ParticleColors: 304074, 28386C, 202C60, 182C54
+			ParticleColors: 255,48,64,116, 255,40,56,108, 255,32,44,96, 255,24,44,84
 			LineTailAlphaValue: 150
-			ParticleSize: 1, 1
 		GlobalLightingPaletteEffect:
 			Red: 0.75
 			Green: 0.85
@@ -542,10 +542,6 @@ Rules:
 		ExplodeCrateAction@bigboom:
 			Weapon: SCUD
 			SelectionShares: 5
-		GiveMcvCrateAction:
-			SelectionShares: 0
-			NoBaseSelectionShares: 1000
-			Units: mobiletent
 	Player:
 		ClassicProductionQueue@Infantry:
 			BuildSpeed: 1
@@ -566,36 +562,6 @@ Rules:
 		CashTrickler:
 			Period: 250
 			Amount: 50
-	MOBILETENT:
-		Inherits: ^Vehicle
-		Valued:
-			Cost: 2000
-		Tooltip:
-			Name: Mobile Tent
-		Selectable:
-			Priority: 4
-		SelectionDecorations:
-			VisualBounds: 21,21
-		Health:
-			HP: 600
-		Armor:
-			Type: Light
-		Mobile:
-			Speed: 85
-			Crushes: wall, mine, crate, infantry
-		RevealsShroud:
-			Range: 4c0
-		MustBeDestroyed:
-			RequiredForShortGame: true
-		BaseBuilding:
-		Transforms:
-			IntoActor: tent
-			Offset: 0,0
-			Facing: 96
-			TransformSounds: placbldg.aud, build5.aud
-			NoTransformNotification: BuildingCannotPlaceAudio
-		RenderSprites:
-			Image: TRUK
 	TENT:
 		Health:
 			HP: 1000
@@ -606,10 +572,10 @@ Rules:
 			Range: 12c0
 		Power:
 			Amount: 0
+		ProductionBar: # Workaround: display this bar over the other one
 		ProductionBar@Defense:
 			ProductionType: Defense
-			Color: 8A8A8A
-		BaseBuilding:
+			Color: 138,138,138
 	FTUR:
 		Buildable:
 			Prerequisites: barracks
@@ -862,7 +828,7 @@ Weapons:
 	TankNapalm:
 		ReloadDelay: 40
 		Range: 8c0
-		Report: aacanon3.aud
+		Report: AACANON3.AUD
 		ValidTargets: Ground
 		Burst: 6
 		BurstDelay: 1
@@ -935,7 +901,7 @@ Weapons:
 	FLAK-23:
 		ReloadDelay: 10
 		Range: 8c0
-		Report: aacanon3.aud
+		Report: AACANON3.AUD
 		ValidTargets: Air, Ground
 		Projectile: Bullet
 			Speed: 1c682
```

File: mods/ra/maps/fort-lonestar/map.yaml [hunk 5]
```diff
@@ -546,12 +533,28 @@ Rules:
...
+			Notification: ironcur9.aud
+			Upgrades: invulnerability
+			Duration: 1200
+		ExplodeCrateAction@bigboom:
+			Weapon: SCUD
+			SelectionShares: 5
+		GiveMcvCrateAction:
+			SelectionShares: 0
+			NoBaseSelectionShares: 1000
+			Units: mobiletent
```
Comment (Mailaender) [inline mods/ra/maps/fort-lonestar/map.yaml]: Needs `ValidFactions` to avoid:

image

**Comment by abcdefg30** [comment]
Yep, the wall commit is new. I wonder why `ParticleSize` changed from `1,1` to `0,0`. Will look into it.

**Comment by Mailaender** [comment]
Looks scarier than it is, but in fact contains mostly the changes from https://github.com/OpenRA/OpenRA/issues/10244 which we already approved. :white_check_mark:

**Comment by abcdefg30** [comment]
The `ParticleSize` change comes from #10203: https://github.com/OpenRA/OpenRA/commit/8fc323602c3ea91719583fa06622d7da75b36232#diff-058bf8510b263ff90d8d9483f8b34744R518

**Comment by pchote** [comment]
Prior to #10203 ParticleSize wasn't used at all for line-type particles, so those definitions were essentially junk.

**Comment by abcdefg30** [comment]
Added the ` ValidFactions` entry.

**Comment by obrakmann** [comment]
Got this when dropping parabombs:
```
Exception of type `System.InvalidOperationException`: Unit `bomblet` does not have a sequence named `open`
  at OpenRA.Graphics.SequenceProvider.GetSequence (System.String unitName, System.String sequenceName) [0x0006b] in /home/oliver/devel/openra/git/OpenRA.Game/Graphics/SequenceProvider.cs:66
```

**Comment by abcdefg30** [comment]
Cherry-picked the fix in again. Weird, I thought this was fixed by @pchote's pr.
Should I remove the `#TODO` note then?

**Comment by abcdefg30** [comment]
Rebased.

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/20db12c65ec3af325edbb6b03b2f2d46fb223293)

**Comment by abcdefg30** [comment]
yay :tada:
