### PR TITLE
Fixed captured buildings producing bot controled units

### LINKED ISSUE #8241: Bot still control units/buildings that have been captured
In RA in mission "survive 01" the bot continue to control vehicles that are hijacked.
In TD in mission "Invasion of Egypt (a)" the bot continue to control buildings i have captured.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/17363560-bot-still-control-units-buildings-that-have-been-captured?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
Should fix #8241 (at least the second part).

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1:

**Comment by penev92** [comment]
Seems legit :+1:

File: mods/cnc/maps/nod02a/nod02a.lua [hunk 1]
```diff
@@ -234,7 +234,7 @@ Tick = function()
 		Nod.MarkCompletedObjective(NodObjective1)
 	end
 
-	if DateTime.GameTime % DateTime.Seconds(3) == 0 and Barracks.IsInWorld then
+	if DateTime.GameTime % DateTime.Seconds(3) == 0 and Barracks.IsInWorld and Barracks.Owner == gdi then
```
Comment (WolfGaming) [inline mods/cnc/maps/nod02a/nod02a.lua]: I wonder which is more efficent
´´´
if DateTime.GameTime % DateTime.Seconds(3) == 0 and Barracks.IsInWorld and Barracks.Owner == gdi
´´´
or
´´´
if Barracks.IsInWorld and Barracks.Owner == gdi and DateTime.GameTime % DateTime.Seconds(3) == 0
´´´

and yes it doesnt really matter since the performance gain either way would be miniscule, but still makes me wonder.

File: mods/cnc/maps/nod02b/nod02b.lua [hunk 2]
```diff
@@ -234,8 +234,8 @@ InsertNodUnits = function()
...
-	if not unit.IsDead then 
-		Trigger.OnIdle(unit, unit.Hunt) 
-	end 
-end
\ No newline at end of file
+IdleHunt = function(unit)
+	if not unit.IsDead then
+		Trigger.OnIdle(unit, unit.Hunt)
+	end
+end
```
Comment (WolfGaming) [inline mods/cnc/maps/nod02b/nod02b.lua]: What is happening here, are you just removing white space endings?

Comment (abcdefg30) [inline mods/cnc/maps/nod02b/nod02b.lua]: Yep.

File: mods/cnc/maps/nod05/nod05.lua [hunk 3]
```diff
@@ -295,9 +295,9 @@ checkProduction = function(player)
 			end
 		end
 		if #UnitsType > 0 then
-			if (type == 'jeep' or type == 'mtnk') and not Factory.IsDead then
+			if (type == 'jeep' or type == 'mtnk') and not Factory.IsDead and Factory.Owner == gdi then
 				Factory.Build(UnitsType)
-			elseif (type == 'e1' or type == 'e2') and not Barracks.IsDead then
+			elseif (type == 'e1' or type == 'e2') and not Barracks.IsDead and Barracks.Owner == gdi then
```
Comment (WolfGaming) [inline mods/cnc/maps/nod05/nod05.lua]: Is the type checking needed here?
Since you already checked if UnitsType was lower then 1.

Comment (abcdefg30) [inline mods/cnc/maps/nod05/nod05.lua]: Above we check if we have units to produce. The units we want to be produced are stored in the `UnitsType` table. If we don't want to produce any, it's "length" is "lower than 1" (zero). Here we check for the actor types inside of the table, as infantry and vehicles aren't produced at the same facility. So, I guess this code is correct. ^^

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/462ae678208350ba85aca2b77a417e0cf4d19510%5E...462ae678208350ba85aca2b77a417e0cf4d19510)
