### PR TITLE
Make Attack turn during its own tick

### LINKED ISSUE #16486: Attack frontal units are not firing when they have to turn
<details>
<summary>Some examples from dog vs rifle interactions:</summary>

DogDriveBy

Dog circle

DogCasual
</details>
<details>
<summary>Rifle vs Thief:</summary>

ThiefDiveBy

Thief circle
</details>
<details>
<summary>Rocket soldier vs Yak:</summary>

PlaneDriveBy

PlaneMiddle
</details>

One of the ways to fix this is by giving units facing tolerance, but I think that it should be done the proper way by making units turn before shooting, opposite of how it is right now

Also one more thing for context, infantry turn instantly to their targets

### LINKED ISSUE #18867: [devtest-20201128] Attack move non honored after first killed
devtest-20201128

Happens around 13:30 - 14:00 in the following replay: [buggy-atk-north-m13-m14.orarep.gz](https://github.com/OpenRA/OpenRA/files/5610800/buggy-atk-north-m13-m14.orarep.gz)

Wasn't able to reproduce with a simple harv attack scenario. It might have to do with the enemy tesla vision, but it's just a wild guess.

### LINKED ISSUE #18871: [devtest-20201128] Attack order doesn't work if the target is on the edge of vision range
Rifle soldiers are issued an attack-move order, engineers are on a simple move command. Rifles don't attack the enemy and just rotate into it until it comes 1 cell closer than vision range limit.
openra_vision_attack_bug

Replay file:
[ra-2020-11-29T090205Z.zip](https://github.com/OpenRA/OpenRA/files/5611911/ra-2020-11-29T090205Z.zip)

### PR DESCRIPTION
**Pull request by abcdefg30**
Queueing a `Turn` child meant we were wasting an additional tick until that child ran. During that time moving targets would already be at a different position, changing `desiredFacing` once again and causing `Attack` to queue another `Turn`. That essentially means `Attack` was stuck in a loop queueing `Turn` activities. Now it directly turns and checks right afterwards if it can attack. If it cannot, the `Attack` activity continues as usual the next tick (and continues turning there, making a `Turn` activity obsolete). This also fixes units not moving into range when they are stuck in the `Turn` child.

Closes #16486.
Closes #18867.
Closes #18871.

Testcase is just starting Allies02.

### CODE REVIEW

**Comment by Orb370** [comment]
Tested in game and works as intended.  :+1:

File: mods/ra/maps/allies-02/allies02.lua [hunk 1]
```diff
@@ -241,11 +241,19 @@ WorldLoaded = function()
...
 	Trigger.AfterDelay(DateTime.Seconds(1), function() Media.PlaySpeechNotification(allies, "MissionTimerInitialised") end)
 
-	RunInitialActivities()
-
-	Reinforcements.Reinforce(player, ConstructionVehicleReinforcements, ConstructionVehiclePath)
-	Trigger.AfterDelay(DateTime.Seconds(5), SendJeepReinforcements)
-	Trigger.AfterDelay(DateTime.Seconds(10), SendJeepReinforcements)
+	--RunInitialActivities()
+
+	--Reinforcements.Reinforce(player, ConstructionVehicleReinforcements, ConstructionVehiclePath)
```
Comment (Phrohdoh) [inline mods/ra/maps/allies-02/allies02.lua:246]: Why comment this out instead of deleting it and retrieving it from history if it is ever needed again?

**Review by pchote — APPROVED** [review]
LGTM. I force pushed over the branch to remove the testcase.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3c7c743b6650b5b50b83029c131fc26c16b2dce1
