### PR TITLE
Fix destroyed truck escaping ra mission sarin-gas-1

### LINKED ISSUE #16839: Sarin Gas 1: Crackdown: Mine killed Truck before waypoint, still GameOver
RA Mission [Sarin Gas 1: Crackdown](https://github.com/OpenRA/OpenRA/blob/release-20190314/mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua) on Release.
sarin1
_(added waypoint to image according to mapeditor)_

A mine killed the (south) escaping truck one cell before the exit waypoint and the game was still lost due to the truck triggering an escape.

[replay.zip min 12](https://github.com/OpenRA/OpenRA/files/3435308/OpenRA-2019-07-26T094745Z.zip)

Tested: Also if a mine is placed directly on the escape-waypoint and a truck reaches it (beeing blowen up) an escape is triggered.

### PR DESCRIPTION
**Pull request by fruestueck**
Fixes #16839

Simply adding `not actor.IsDead ` to the condition would prevent first half of 16839.

By checking for `actor.IsIdle` (and resceduling the Trigger) the truck has to finish its move and trigger a possible mine before that.

### CODE REVIEW

File: mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua [hunk 1]
```diff
@@ -42,27 +42,21 @@ SetupTriggers = function()
...
-			greece.MarkFailedObjective(objDestroyAllTrucks)
-		end
-	end)
+	SetTrukTrigger(TruckEscapeCenter.Location, triggerlose1)
+	SetTrukTrigger(EscapeNorth10.Location, triggerlose2)
+	SetTrukTrigger(EscapeSouth5.Location, triggerlose3)
+end
 
-	Trigger.OnEnteredFootprint({ EscapeSouth5.Location }, function(actor, triggerlose3)
+SetTrukTrigger = function(location, trigger)
```
Comment (abcdefg30) [inline mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua]: The `trigger` argument here can be removed. (It is unused, since the function declared in `OnEnteredFootprint` overwrites it with its own parameter definition.)

File: mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua [hunk 2]
```diff
@@ -42,27 +42,21 @@ SetupTriggers = function()
...
 		if actor.Owner == ussr and actor.Type == "truk" then
-			Trigger.RemoveProximityTrigger(triggerlose3)
-			actor.Destroy()
-			greece.MarkFailedObjective(objDestroyAllTrucks)
+			if actor.IsIdle then
+				Trigger.RemoveProximityTrigger(trigger)
+				actor.Destroy()
+				greece.MarkFailedObjective(objDestroyAllTrucks)
+			elseif not actor.IsDead then
+				Trigger.AfterDelay(DateTime.Seconds(0.2), function() SetTrukTrigger(location, trigger) end)
```
Comment (abcdefg30) [inline mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua]: We are not removing the trigger, so setting it again here looks bogus.

File: mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua [hunk 3]
```diff
@@ -42,27 +42,21 @@ SetupTriggers = function()
...
-	Trigger.OnEnteredFootprint({ EscapeNorth10.Location }, function(actor, triggerlose2)
-		if actor.Owner == ussr and actor.Type == "truk" then
-			Trigger.RemoveProximityTrigger(triggerlose2)
-			actor.Destroy()
-			greece.MarkFailedObjective(objDestroyAllTrucks)
-		end
-	end)
+	SetTrukTrigger(TruckEscapeCenter.Location, triggerlose1)
+	SetTrukTrigger(EscapeNorth10.Location, triggerlose2)
+	SetTrukTrigger(EscapeSouth5.Location, triggerlose3)
```
Comment (abcdefg30) [inline mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua]: Generally, I don't think we want to set three triggers here, but just set one trigger that has all three locations:
`Trigger.OnEnteredFootprint({ a, b, c }, function...`
(We don't need an extra method then as well.)

File: mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua (hunk 2 above)
Comment (abcdefg30) [reply mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua]: By the way: `DateTime.Seconds` only takes integers as argument, so in fact 0.2 will just get rounded down to 0.

**Review by abcdefg30 — COMMENTED** [review]
I guess you were setting new triggers because the actor is not idle the first time it enters the destination location. Can we try to add an idle trigger to the truck instead?

**Comment by abcdefg30** [comment]
Tbh, I think the cleanest solution would be to actually let the trucks move outside of the playable area before removing them. That would be left to another PR though.

File: mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua (hunk 3 above)
Comment (fruestueck) [reply mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua]: Thank you! I'll make the changes early next week.

File: mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua (hunk 2 above)
Comment (fruestueck) [reply mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua]: Okay. I did't find a waitTicks(1) eather. Alternativly we could check for an mine occupying the field as well. I am happy for any other solution : )

**Comment by fruestueck** [comment]
> Tbh, I think the cleanest solution would be to actually let the trucks move outside of the playable area before removing them.

I tried it but failed with my limited knowledge about the available lua cmds. A simple move to one cell outside the map won't work as far as I got to test it.
What would be the the preferred function?

**Comment by abcdefg30** [comment]
> What lua function would be suitable?

None as far as I know, hence I said we should leave it to another PR to keep things simple here (imho).

**Comment by fruestueck** [comment]
Fixed and rebased.

File: mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua [hunk 4]
```diff
@@ -41,28 +41,16 @@ SetupTriggers = function()
...
-
-	Trigger.OnEnteredFootprint({ EscapeSouth5.Location }, function(actor, triggerlose3)
+	
+	Trigger.OnEnteredFootprint({ TruckEscapeCenter.Location, EscapeNorth10.Location, EscapeSouth5.Location }, function(actor, trigger)
 		if actor.Owner == ussr and actor.Type == "truk" then
-			Trigger.RemoveProximityTrigger(triggerlose3)
-			actor.Destroy()
-			greece.MarkFailedObjective(objDestroyAllTrucks)
+			Trigger.OnIdle(actor, function ()
+				if actor.IsIdle then
```
Comment (abcdefg30) [inline mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua]: This does not make sense, if this function runs the actor is certainly idle.

**Review by abcdefg30 — COMMENTED** [review]
This is not exactly what I had in mind. I thought about replacing the footprint trigger with an idle trigger. Since we know which route each truck is going to take when applying the idle trigger (if you do it after it got the move command), you can check if the truck reached its destination inside the trigger. If it did, the mission is over, otherwise the truck should do another move to the destination.

File: mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua (hunk 4 above)
Comment (fruestueck) [reply mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua]: I was asleep from the looks of it. Thanks!

**Comment by fruestueck** [comment]
Updated.

I've merged the EscapeRouteNorth and South functions as they are pretty the same.
The following line was removed as I'm not sure if it is needed anymore. If someone could explain I'd be happy.
Trigger.RemoveProximityTrigger(triggerlose)

File: mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua [hunk 5]
```diff
@@ -124,25 +100,35 @@ SendPatrol = function(mammoth)
...
-MoveTruckSouth = function(truck)
-	if truck.IsDead then
-		return
-	else
-		Media.DisplayMessage("Convoy truck attempting to escape!")
-		Media.PlaySoundNotification(greece, "AlertBleep")
-		Utils.Do(TruckEscapeSouth, function(waypoint)
-			truck.Move(waypoint.Location)
+SetTruckEscapeTrigger = function (actor, escape)
+	if actor.Owner == ussr and actor.Type == "truk" then
```
Comment (abcdefg30) [inline mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua]: We don't need this check any more. At the time this function is running we know that `actor` is a truck and that it is owned by the soviets.

File: mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua [hunk 6]
```diff
@@ -124,25 +100,35 @@ SendPatrol = function(mammoth)
...
 
-MoveTruckSouth = function(truck)
-	if truck.IsDead then
-		return
-	else
-		Media.DisplayMessage("Convoy truck attempting to escape!")
-		Media.PlaySoundNotification(greece, "AlertBleep")
-		Utils.Do(TruckEscapeSouth, function(waypoint)
-			truck.Move(waypoint.Location)
+SetTruckEscapeTrigger = function (actor, escape)
```
Comment (abcdefg30) [inline mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua]: Style nit: Please remove the space after `function`.

File: mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua [hunk 7]
```diff
@@ -124,25 +100,35 @@ SendPatrol = function(mammoth)
...
+	if actor.Owner == ussr and actor.Type == "truk" then
+		Trigger.OnIdle(actor, function ()
```
Comment (abcdefg30) [inline mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua]: Same here.

**Review by abcdefg30 — COMMENTED** [review]
Untested, but looks good now!

> The following line was removed as I'm not sure if it is needed anymore. If someone could explain I'd be happy. `Trigger.RemoveProximityTrigger(triggerlose)`

You are right, we don't need that any more. Since you are not setting any triggers, we also don't need to remove them.

I think merging the functions (your second point) would be cleaner, but I don't think it is required, so up to you.

> We could also scratch the check for the escapelocation as the trucks will never go idle until they reach the escape waypoint afaik. If a waypoint is blocked, they just wait until it's unblocked.

Usually I would agree. However I think it is good to have some sort of save guard against weird things like https://github.com/OpenRA/OpenRA/issues/5968#issuecomment-412546323 happening.

File: mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua (hunk 6 above)
Comment (fruestueck) [reply mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua]: I should use something else than notepad++ to highlight useless spaces

File: mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua (hunk 5 above)
Comment (fruestueck) [reply mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua]: right

**Comment by fruestueck** [comment]
TruckEscapeRoutes merged and updated.

**Review by abcdefg30 — APPROVED** [review]
Nice cleanup!

**Comment by reaperrr** [comment]
Since we need (at least) one more playtest anyway, might as well pick this to prep if we get another review in time.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/48412a3f6391db28bd8faf0b7e42f6bfeed828cc

de330daf85
